"use client";

import { Oswald } from "next/font/google";
import "./globals.css";
import { Box, CssBaseline} from "@mui/material";

const inter = Oswald({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Box>
      <CssBaseline />
      <body>{children}</body>
     </Box>

  );
}
